### ISSUE TITLE
Running for new season

### ISSUE THREAD

**Issue by DigitalTechnicality** [Spencer-Weston/NBA_bet#10]
There are a few issues right now when running for the 2019-2020 NBA season. I am trying to comb through and fix as many as possible.

**Comment by Spencer-Weston** [comment]
Hi DigitalTechnicality,
Are you using the Master branch? If so, I would not use your time fixing those issues. As designed, the database tables are not in any kind of normal form (along with some other issues). However, if you'd like to help, please take a look at the reorganization branch where I'm working on normalizing the databases. That branch will become master in the coming weeks, and will be far more resilient. Let me know if that helps, or if I can help in another way.
